services:
  backend:
    build:
      context: ./backend  # points to your backend folder
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./frontend  # Path to the frontend directory
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
