version: '3'

services:
  backend:
    build:
      context: ./backend   # Path to the backend directory
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend  # Path to the frontend directory
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
